//! ISO 639-1 language codes (TMDB's `original_language`) → English names.

pub fn name(code: &str) -> Option<&'static str> {
    Some(match code.trim().to_lowercase().as_str() {
        "en" => "English",
        "da" => "Danish",
        "sv" => "Swedish",
        "no" | "nb" | "nn" => "Norwegian",
        "fi" => "Finnish",
        "is" => "Icelandic",
        "de" => "German",
        "nl" => "Dutch",
        "fr" => "French",
        "es" => "Spanish",
        "pt" => "Portuguese",
        "it" => "Italian",
        "pl" => "Polish",
        "cs" => "Czech",
        "sk" => "Slovak",
        "hu" => "Hungarian",
        "ro" => "Romanian",
        "bg" => "Bulgarian",
        "el" => "Greek",
        "tr" => "Turkish",
        "ru" => "Russian",
        "uk" => "Ukrainian",
        "sr" => "Serbian",
        "hr" => "Croatian",
        "bs" => "Bosnian",
        "sl" => "Slovenian",
        "et" => "Estonian",
        "lv" => "Latvian",
        "lt" => "Lithuanian",
        "ga" => "Irish",
        "cy" => "Welsh",
        "ca" => "Catalan",
        "eu" => "Basque",
        "gl" => "Galician",
        "ar" => "Arabic",
        "he" => "Hebrew",
        "fa" => "Persian",
        "ku" => "Kurdish",
        "hi" => "Hindi",
        "bn" => "Bengali",
        "pa" => "Punjabi",
        "ta" => "Tamil",
        "te" => "Telugu",
        "ml" => "Malayalam",
        "kn" => "Kannada",
        "mr" => "Marathi",
        "ur" => "Urdu",
        "zh" | "cn" => "Chinese",
        "ja" => "Japanese",
        "ko" => "Korean",
        "th" => "Thai",
        "vi" => "Vietnamese",
        "id" => "Indonesian",
        "ms" => "Malay",
        "tl" => "Tagalog",
        "sw" => "Swahili",
        "af" => "Afrikaans",
        "zu" => "Zulu",
        "xx" => return None, // "no language"
        _ => return None,
    })
}
